### ISSUE TITLE
Error while creating data - Can you please review Config.py?

### ISSUE THREAD

**Issue by darkdevahm** [MediaBrain-SJTU/SyncNet#7]
Traceback (most recent call last):
  File "create_data_LAdet.py", line 638, in <module>
    create_data([config, nusc, current_agent, config_global, scene_list])
  File "create_data_LAdet.py", line 245, in create_data
    config.savepath, str(scene_idx) + "_" + str(save_seq_cnt)
AttributeError: 'Config' object has no attribute 'savepath'

**Comment by Chezacar** [comment]
Sorry for inconvenience. The coperception repository modified the Config.py, causing this bug. You may try coperception with commit id 59e8fa36a315bf652bf2eb9f0c64dc3cbca61d34 and check issues in https://github.com/coperception/coperception/issues/7

**Comment by scdrand23** [comment]
Hi,
The issue you linked seems to discuss split set overlap. Not this
I can run smoothly the original DiscoNet. But create_data_LAdet.py throws an error. 
How can I solve this, please?
